fix: header & copyright margin, jetbrains mono font
Innei/Shiro pull request #155
Opened 2023-11-13 02:12 UTC by zhuozhiyongde

### Description

增加了 Copyright 版权信息同正文的间距，便于区分。

移除了 Header 的左边距，因为这在小尺寸屏幕下会导致正文层叠可见。（对于右边距，因为是滚动条的空间所以无所谓，不过我发现好像 bilibili 的滚动条是悬浮不影响页面尺寸的（Safari/Chrome），不知道是否可以借鉴一下。

![Cleanshot-2023-11-13-at-10 08 48](https://github.com/Innei/Shiro/assets/36695271/247d3cfe-74ee-4156-821d-925964c26f73)

引入了 JetBrains-Mono 的 Google Font API，便于用户使用。

### Linked Issues

### Additional context

目前右侧工具栏也有层叠问题，但是不太清楚怎么修复。

![image](https://github.com/Innei/Shiro/assets/36695271/3a07a842-0e51-4722-9c7e-25fa2f7c59d7)

2023-11-13 10:14 UTC, Innei requested changes
这里会去掉产生打开 modal 的 CLS

2023-11-13 10:15 UTC, Innei commented on src/components/layout/header/internal/HeaderWithShadow.tsx
> -        'fixed left-0 right-0 top-0 z-[9] ml-[calc(100vw-100%)] h-[4.5rem] overflow-hidden transition-shadow duration-200',
这里去掉会导致打开 modal 时 header 的 CLS

2023-11-13 10:15 UTC, Innei commented on src/styles/webfont.css
> +@font-face {
不喜欢，你可以自己加

2023-11-13 10:36 UTC, zhuozhiyongde commented
那文字溢出有什么解决方法吗（

2023-11-13 10:38 UTC, zhuozhiyongde commented on src/styles/webfont.css
> +@font-face {
我没有修改 Tailwindcss 的 Config 文件，只是引入了一下字体文件，所以现在看起来是没有变化的。我想的是如果用户有需要的话就可以通过删除配置文件排序考前的字体就行了（

2023-11-13 14:14 UTC, Innei commented
> 那文字溢出有什么解决方法吗（

侧栏图标么，页面滚动到底是会这样的，因为向上偏移了 100%

2023-11-13 14:31 UTC, zhuozhiyongde commented
> > 那文字溢出有什么解决方法吗（
> 
> 
> 
> 侧栏图标么，页面滚动到底是会这样的，因为向上偏移了 100%

不，我指的是标题栏Header左侧哪里

2023-12-05 03:42 UTC, Innei approved these changes

2023-12-05 03:43 UTC, Innei commented on tailwind.config.ts
> -        mono: `"OperatorMonoSSmLig Nerd Font","Cascadia Code PL","FantasqueSansMono Nerd Font","operator mono",JetBrainsMono,"Fira code Retina","Fira code","Consolas", Monaco, "Hannotate SC", monospa
为什么把这些删了

2023-12-05 03:50 UTC, zhuozhiyongde commented on tailwind.config.ts
> -        mono: `"OperatorMonoSSmLig Nerd Font","Cascadia Code PL","FantasqueSansMono Nerd Font","operator mono",JetBrainsMono,"Fira code Retina","Fira code","Consolas", Monaco, "Hannotate SC", monospa
草 忘了忽略这部分更改了 这个是我个人的设置 偏好JetBrains Mono

2023-12-05 03:54 UTC, zhuozhiyongde commented on tailwind.config.ts
> -        mono: `"OperatorMonoSSmLig Nerd Font","Cascadia Code PL","FantasqueSansMono Nerd Font","operator mono",JetBrainsMono,"Fira code Retina","Fira code","Consolas", Monaco, "Hannotate SC", monospa
不对 是我后续更改一直在往上推送...发PR的时候我应该没删

2023-12-05 03:57 UTC, zhuozhiyongde commented on tailwind.config.ts
> -        mono: `"OperatorMonoSSmLig Nerd Font","Cascadia Code PL","FantasqueSansMono Nerd Font","operator mono",JetBrainsMono,"Fira code Retina","Fira code","Consolas", Monaco, "Hannotate SC", monospa
我加回来吧先，不太清楚这种情况应该怎么用 Git 解决，PR 为啥一直同步我的主分支的 commit 啊

2023-12-05 03:59 UTC, zhuozhiyongde commented
@Innei 已经加回来了

2023-12-05 04:37 UTC, merged