feat: add fetchLeetCodeQuestionData function to LinkCard
Innei/Shiro pull request #439
Opened 2024-08-21 15:19 UTC by liyown

### Description

添加了LeetCode LinkCard的实现

### Linked Issues
#438  
### Additional context
效果图
![image](https://github.com/user-attachments/assets/f00f5b47-7c5c-4471-8d89-bb4858f9046c)
使用方法：在云函数创建一个serverless
名字：shiro
引用：leetcode
数据类型：Function
请求方式：POST

```ts
export default async function handler(ctx: Context) {
  const requestBody =ctx.req.body
  // 通用的 GraphQL 请求函数
  const response = await fetch('https://leetcode.cn/graphql/', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(requestBody),
  });
  if (!response.ok) {
    throw new Error('Failed to fetch data from LeetCode API');
  }
  return await response.json();

}
```

2024-08-21 15:25 UTC, liyown commented
样式和布局是自己瞎调的，大佬要是可以优化一下就更好了

2024-08-21 15:33 UTC, Innei commented
题目难度 放到最左边，这样会提交好

2024-08-21 15:35 UTC, liyown commented
麻烦大佬改一下啦，我电脑关闭了，起服务弄了我好久，还没学过nextjs

2024-08-21 15:38 UTC, Innei requested changes

2024-08-21 15:38 UTC, Innei commented on src/components/ui/link-card/LinkCard.tsx
> +      console.log('----------questionTitleData:', questionTitleData)
这个不要

2024-08-21 15:38 UTC, Innei commented on src/components/ui/link-card/LinkCard.tsx
> +      // 第三个请求：获取题目标签
这样发请求太慢了，三个请求一起 batch 掉

2024-08-21 15:38 UTC, Innei commented on src/components/ui/link-card/LinkCard.tsx
> +              {questionTitleData.difficulty}
这个放左边

2024-08-21 15:38 UTC, Innei commented on src/components/ui/link-card/LinkCard.tsx
> +              style={{ fontWeight: 'bold', marginLeft: '24px' }}
用 tailwind css 去写，不要 inline style

2024-08-21 15:38 UTC, Innei commented on src/components/ui/link-card/LinkCard.tsx
> +      setFullUrl(`https://leetcode.cn/problems/${id}/`)
去掉尾斜杠

2024-08-21 15:38 UTC, Innei commented
Rebase 一下

2024-08-21 15:40 UTC, Innei commented
LinkCard 不建议在 Markdown 里直接使用，应该用 `BlockLinkRenderer` 去调用 LinkCard。

所以 `BlockLinkRenderer` 也得写一下。

`src/components/ui/markdown/renderers/LinkRenderer.tsx`

2024-08-21 15:41 UTC, liyown commented on src/components/ui/link-card/LinkCard.tsx
> +      // 第三个请求：获取题目标签
这个接口不支持 batch 放在serverless还是一个一个发的

2024-08-21 16:22 UTC, liyown commented
![image](https://github.com/user-attachments/assets/eeee5a2c-4eea-434c-a36d-ab0cf6edcc78)
 
BlockLinkRenderer 重写了

2024-08-22 03:19 UTC, liyown commented on src/components/ui/link-card/LinkCard.tsx
> +      // 第三个请求：获取题目标签
已经batch

2024-08-22 03:22 UTC, liyown commented
我想题目提交的卡片也加上去，我测试发现这个接口需要cookie，不过这个cookie的过期时间是半个月，有必要加上去吗

2024-08-22 05:44 UTC, Innei commented
> 我想题目提交的卡片也加上去，我测试发现这个接口需要cookie，不过这个cookie的过期时间是半个月，有必要加上去吗

不用了吧

2024-08-22 05:45 UTC, Innei commented
我改不了你的分支，只能你自己改

2024-08-22 09:27 UTC, liyown commented
> 我改不了你的分支，只能你自己改

我这里测试的时候发现一个问题，思考页面 无法渲染，求解
![image](https://github.com/user-attachments/assets/2a2372fc-56b6-479e-a056-9553b9a5ec48)
![image](https://github.com/user-attachments/assets/99638202-46e7-42b7-a89c-1edd3eac891a)

2024-08-23 09:05 UTC, merged