build: add Dockerfile
Innei/Shiro pull request #54
Opened 2023-08-04 09:55 UTC by hqwuzhaoyi

I plan to add a Dockerfile for possible local deployment needs.

The temporary process is as follows

Change the `.env.template` file

```
docker build -t shiro . --load       
```

```
docker run --name shiro -d -p 2233:3000 shiro
```

I studied the next packaging and temporarily cannot put the NEXT env in the environment variables of docker run. I can only package it locally first.

<img width="1411" alt="CleanShot 2023-08-04 at 17 35 58@2x" src="https://github.com/Innei/Shiro/assets/44605072/254fd5cf-323b-4fb2-bcff-dfdadb5f9420">

2023-08-06 15:27 UTC, Innei requested changes

2023-08-06 15:27 UTC, Innei commented on Dockerfile
> +EXPOSE 3000
```suggestion
EXPOSE 2323
```

2023-08-06 15:27 UTC, Innei commented on Dockerfile
> +
```suggestion

ENV NODE_ENV production
ARG BASE_URL
ENV BASE_URL=${BASE_URL}
ENV NEXT_PUBLIC_API_URL=${BASE_URL}/api/v2
ENV NEXT_PUBLIC_GATEWAY_URL=${BASE_URL}

# and other docker env inject
```

2023-08-06 15:28 UTC, Innei commented on Dockerfile
> +
Refer: https://github.com/mx-space/kami/blob/master/Dockerfile

2023-08-07 03:05 UTC, hqwuzhaoyi commented
@Innei I just tried it, but in the next `appDir` mode, the environment variables need to be generated on page `build`. If they are not placed in env before building, packaging will not work properly.

![CleanShot 2023-08-07 at 10 51 02](https://github.com/Innei/Shiro/assets/44605072/af48c6a7-402f-450a-81a2-fdf631c0968b)

I think we can create the .env file first, or put ARG before Build.

2023-08-07 03:06 UTC, hqwuzhaoyi commented
> @Innei I just tried it, but in the next `appDir` mode, the environment variables need to be generated on page `build`. If they are not placed in env before building, packaging will not work properly.
> 
> ![CleanShot 2023-08-07 at 10 51 02](https://user-images.githubusercontent.com/44605072/258687399-af48c6a7-402f-450a-81a2-fdf631c0968b.png)
> 
> I think we can create the .env file first, or put ARG before Build.

I will commit it immediately.

2023-08-07 04:05 UTC, hqwuzhaoyi commented
@Innei 
I added a docker-compose.yml.

Now just need to change the args inside.

Then execute 

```
docker compose up -d
```

or use docker command

```
docker build \
 --build-arg BASE_URL=BASE_URL \
 --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
 --build-arg CLERK_SECRET_KEY=CLERK_SECRET_KEY \
 -t shiro . --load
```

```
docker run --name shiro -d -p 2323:2323 shiro
```

2023-08-07 05:07 UTC, Innei approved these changes
Thank you!

2023-08-07 05:07 UTC, merged